### ISSUE TITLE
Road to V1

### ISSUE THREAD

**Issue by astahmer** [astahmer/openapi-zod-client#26]
## v1 should have :

- [x] [handle OpenAPI schema default values](https://github.com/astahmer/openapi-zod-client/issues/7)
- [x] [handle OpenAPI format (dates/uri](https://github.com/astahmer/openapi-zod-client/issues/8)
- [x] [handle OpenAPI string|number constraints](https://github.com/astahmer/openapi-zod-client/issues/9)
- [x] [support other requestFormats than json](https://github.com/astahmer/openapi-zod-client/issues/14) / [support file upload](https://github.com/astahmer/openapi-zod-client/issues/18)

## (maybe) after v1 :

- [x] splitting 1 OpenAPI spec input into multiple files output (could be by tags ? by path ? by method ?) 
idea [from this article](https://zenn.dev/ki504178/articles/openapi_zod_client) 

> However, since the generated files are currently combined into one file, in
the case of a system configuration in which API requests are made directly from the front end,
there is a concern that the bundle size of each page that uses the API client will increase.

- [ ] support swagger v2 by auto-converting it to v3 (if possible ?) before parsing it 
- [x] provide a `schemas` template for exporting the schemas only:  no zodios import/usage, just openapi -> zod (+ typescript if there are recursive schemas) -> related to [this](https://github.com/astahmer/openapi-zod-client/issues/19)
- [x] internal implementation rewrite ? current state of the repo is a quite a mess, what started as a quick PoC somehow got a bit of attention (and also needed it at work) so I tried to deliver ASAP
